# Site
name: "CORAL-Project"
title: "CORAL-Project"
description: "A CSA compliant self-assessment and basic level certification framework"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 


# Authors
authors:
  ggh:
    name: Gabriela Gheorghe
    display_name: Gabriela G.
    avatar: 'assets/images/avatar.png'
    email: info@coral-project.org
    web: https://www.nc3.lu
    description: "Project Manager"
  fma:
    name: Fabien Mathey
    display_name: Fabien M.
    avatar: 'assets/images/avatar.png'
    email: info@coral-project.org
    web: https://www.nc3.lu
    description: "Former poject Assistant"
  dko:
    name: Dominique Kogue
    display_name: Dominique K.
    avatar: 'assets/images/avatar.png'
    email: info@coral-project.org
    web: https://www.nc3.lu
    description: "Project Assistant"

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - kramdown-syntax-coderay
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
# paginate: 6
# paginate_path: /blog/page:num/

pagination:
  enabled: true
  per_page: 6
  permalink: '/blog/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
